website/models.py
"""
Purpose: 
    1. We wnat to store different database models, we make this class:

    2. We crete classes for teh ojects like User, Notes, and more. 

    3. We give the info we want to save for each object. 
        Ex: User: Name, email, ID, ...
        Ex: Note: Text, date, and more
    
    4. How to asccosiate different notes data to different users?ie. what if a user have multiply notes, how should they connect with one another.
        - Main Concept: Foreign Key vs Primary Key
        - Foreign key: A column in your database that  references a column of another database. 
        So in this instance, for every: 
        - single note: store the ID
    
    5. We also want that all users to find all of their notes. 
    This is example of one to many
        - we have one to one
        - we have many to one
        - for more info read ducumentation. 
    Ex: 
    User_table:
        id	        email
        1	        a@x.com

    Note_table: 
        id	        text	    user_id
        5	        "hi"	       1
        6	        "hey"	       1

    User class: 
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    
    Notes class:
    notes = db.relationship('Note') 
    --> This gives all the notes (id = 5,6) to user_id=1

"""


from . import db
## Give objects for flask login:
from flask_login import UserMixin
from sqlalchemy.sql import func


class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    
    # Length of text <= 10000
    text = db.Column(db.String(10000))

    # store the date + timezone 
    # --> needs the sqlalchemy.sql library
    date = db.Column(db.DateTime(timezone=True), default=func.now())

    # -----------------------------------------
    # Connecting the data(Note) and the User
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    # This user_id, will always save the id of the user
    # Inputs: we need db.Integer + db.ForeignKey('user.field'), which in this case it is the id. 


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)

    # email length <= 150 char long + unique 
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    firstName = db.Column(db.String(150))
    notes = db.relationship('Note')

website/__init__.py
# This helps to make the website as a package to import. 

# First thing to do: Create an app with flask:
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    # Initialuze app:
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)
    
    from .views import views
    from .auth import auth


    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Note
    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

def create_database(app):
    """
    Checks if the database exists, and if not, creates a new one.

    Parameters
    ----------
    app : Flask
        The Flask app object.

    Returns
    -------
    None
    """
    if not path.exists('website/' + DB_NAME):
        with app.app_context():
            db.create_all()
        print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user

# This has so much routs here, has URL, 

auth = Blueprint('auth', __name__) # Recc: call the same name

# We now create more routs: login, logout, sign up:
@auth.route('/login', methods=['GET', 'POST'])
def login():
    flash("DEBUG: route loaded", "success")
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        # Filter the users by this email, adn give teh first result:
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password! try again.', category='error')
        else: 
            flash('User does not exist', category='error')



    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=["GET", "POST"])
def sign_up():
    flash("DEBUG: route loaded", "success")
    if request.method == 'POST':
        email = request.form.get('email')
        firstName = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
    

    # Now we wanna check if the information is valid or not:

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exist', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 4 characters.', category='error')
        elif len(firstName) < 2:
            flash('First name must be greter than 1 characters.', category='error')
        elif len(password1) != len(password2):
            flash('Passwords don\'t match', category='error')
        elif len(password1) < 7: 
            flash('Password should be at least 7 characters', category='error')
            # The data is right and we can enter it to our database. 
        else: 
            # Making a user:
            new_user = User(
                email=email,
                firstName=firstName,
                password=generate_password_hash(password1, method='pbkdf2:sha256')
            )
            db.session.add(new_user)
            db.session.commit()
            login_user(user, remember=True)

            flash('Accounts created!', category='success')

            # Now redirect to the home_page
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

website/views.py
# We will crete teh first routs, like login page, home-page, 

# First we start with flask:
from flask import Blueprint, render_template, request, flash, redirect, url_for
# This has so much routs here, has URL, 
from flask_login import login_required, current_user
from .models import User, Note
from . import db


views = Blueprint('views', __name__) # Recc: call the same name

@views.route('/delete-note', methods=['POST'])
@login_required
def delete_note():
    data = request.get_json()
    note_id = data.get('noteId')

    note = Note.query.get(note_id)
    if note and note.user_id == current_user.id:
        db.session.delete(note)
        db.session.commit()

    return jsonify({})

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST': 
        note = request.form.get('note')#Gets the note from the HTML 

        if len(note) < 1:
            flash('Note is too short!', category='error') 
        else:
            new_note = Note(text=note, user_id=current_user.id)  #providing the schema for the note 
            db.session.add(new_note) #adding the note to the database 
            db.session.commit()
            flash('Note added!', category='success')

    return render_template("home.html", user=current_user)

website/templates/base.html
<!-- This is the base template: like header, footer, adn more. And then we over-ride it. -->

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width", initial-scale="1" />
        <!-- This is a block and it is used for templates: -->
        

        <title>
            {% block title %}Default Title{% endblock %}
        </title>
        <link rel="stylesheet"
          href="{{ url_for('static', filename='base_style.css') }}">

    </head>
    
    <body>
        <!-- Creating a header --> 

        <div class="container_header"> 
              
            <p class="welc_txt"> Welcome </p>

            {% if user.is_authenticated %}
            <a href="{{ url_for('views.home') }}" class="nav-btn">Home</a>
            <a href="{{ url_for('auth.logout') }}" class="nav-btn">Logout</a>
            {% else %}
            <a href="{{ url_for('auth.login') }}" class="nav-btn">Login</a>
            <a href="{{ url_for('auth.sign_up') }}" class="nav-btn">Sign Up</a>
            {% endif %}

        </div>

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert {{ category }}">
                    {{ message }}
                <button class="close-btn">&times;</button>
                </div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        <div class="container" style="padding-top: 70px;" >
            {% block content %}
            {% endblock %}
        </div>

    
        <!-- Loading from static, a javascript file -->
        <script 
            type="text/javascript"
            src="{{ url_for('static', filename='base.js')}}"> 
        </script>



    </body>
</html>

website/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}
<h1 class="page-title">Notes</h1>

<ul class="notes-list" id="notes">
  {% for note in user.notes %}
    <li class="note-item">
      <span class="note-text">{{ note.text }}</span>

      <button
        type="button"
        class="note-delete"
        onClick="deleteNote({{ note.id }})"
        aria-label="Delete note"
      >
        &times;
      </button>
    </li>
  {% endfor %}
</ul>

<form method="POST" class="note-form">
  <textarea name="note" id="note" class="note-input"></textarea>

  <div class="note-submit-wrapper">
    <button type="submit" class="note-submit">Add Note</button>
  </div>
</form>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<form method="POST">
    <h3> Login </h3>
    <!-- Email: -->
    <div class="Email">
        <label for="email">Email Address</label>
        <input 
            type="email" 
            class="input-email" 
            id="email"
            name="email" 
            placeholder="Enter email" 
        />
    </div>
    
    <!-- Password: -->
    <div class="password1">
        <label for="password1">Password</label>
        <input 
            type="password" 
            class="password1" 
            id="password"
            name="password" 
            placeholder="Enter password" 
        />
    </div>


    <br />
    <button type="submit" class="submit-btn"> 
        Login  
    </button>
{% endblock %}

website/templates/logout.html
{% extends "base.html" %}

{% block title %}Logout{% endblock %}

{% block content %}
    <h1>This is the logout page</h1>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
    <h1>This is the sign up page</h1>
    <form method="POST">
        <h3> Sign Up</h3>
        <!-- Email: -->
        <div class="Email">
            <label for="email">Email Address</label>
            <input 
                type="email" 
                class="input-email" 
                id="email"
                name="email" 
                placeholder="Enter email" 
            />
        </div>

        <!-- First Name: -->
        <div class="firstName">
            <label for="firstName">First Name</label>
            <input 
                type="text" 
                class="input-firstName" 
                id="firstName"
                name="firstName" 
                placeholder="Enter first name" 
            />
        </div>

        <!-- Password: -->
        <div class="password1">
            <label for="password1">Password</label>
            <input 
                type="password" 
                class="password1" 
                id="password1"
                name="password1" 
                placeholder="Enter password" 
            />
        </div>

        <!-- Confirm Password: -->
        <div class="password2">
            <label for="password2">Password</label>
            <input 
                type="password" 
                class="password2" 
                id="password2"
                name="password2" 
                placeholder="Confirm password" 
            />
        </div>

        <br />
        <button type="submit" class="submit-btn"> 
            Submit  
        </button>
    </form>
{% endblock %}